"""add kick reasons and room kicks

Revision ID: 51d4931bc224
Revises: 7285ed506b9c
Create Date: 2026-05-19 22:56:26.455082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d4931bc224'
down_revision: Union[str, Sequence[str], None] = '7285ed506b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kick_reasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('room_kicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('kicked_by', sa.UUID(), nullable=True),
    sa.Column('reason_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('kicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kicked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['room_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reason_id'], ['kick_reasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_kicks_participant_id'), 'room_kicks', ['participant_id'], unique=False)
    op.create_index(op.f('ix_room_kicks_room_id'), 'room_kicks', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_kicks_room_id'), table_name='room_kicks')
    op.drop_index(op.f('ix_room_kicks_participant_id'), table_name='room_kicks')
    op.drop_table('room_kicks')
    op.drop_table('kick_reasons')
    # ### end Alembic commands ###
